apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx-test
    app.kubernetes.io/name: nginx-test
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: nginx-test
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
