apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-config
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/cmomodo/kubernetes.git
    targetRevision: main
    path: EKS/gitops/workloads/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
