apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
  labels:
    app.kubernetes.io/name: nginx-test
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: gitops
spec:
  project: default
  sources:
    - repoURL: https://github.com/cmomodo/kubernetes.git
      targetRevision: main
      path: EKS/gitops/charts/nginx-test
      helm:
        releaseName: nginx-test
        valueFiles:
          - $values/EKS/helm-values/nginx-test.yaml
    - repoURL: https://github.com/cmomodo/kubernetes.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
