apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-replicaset
  labels:
    app: myapp
spec:
  replicas: 4
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: nginx
      labels:
        env: production
    spec:
      containers:
      - name: nginx
        image: nginx:latest
