apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: monitoring-secrets
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/cmomodo/kubernetes.git
    targetRevision: main
    path: EKS/gitops/workloads/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
